batch_size: 2
iters: 40000

train_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: RandomHorizontalFlip
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val

model:
  type: ocrnet
  backbone:
    type: HRNet_W18
    pretrained: dygraph/pretrained_model/hrnet_w18_ssld/model
  num_classes: 19
  in_channels: 270

optimizer:
  type: sgd

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9

loss:
  type: CrossEntropy
