EVAL_CROP_SIZE: (513, 513) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (513, 513) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: u"stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (640, 640) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    RICH_CROP:
        ENABLE: False
        ASPECT_RATIO: 0.33
        BLUR: True
        BLUR_RATIO: 0.1
        FLIP: True
        FLIP_RATIO: 0.2
        MAX_ROTATION: 15
        MIN_AREA_RATIO: 0.5
        BRIGHTNESS_JITTER_RATIO: 0.5
        CONTRAST_JITTER_RATIO: 0.5
        SATURATION_JITTER_RATIO: 0.5
BATCH_SIZE: 8
MEAN: [104.008, 116.669, 122.675]
STD: [1.0, 1.0, 1.0]
DATASET:
    DATA_DIR: "./data/COCO2014/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 21
    TEST_FILE_LIST: "data/COCO2014/VOC_ImageSets/val.txt"
    TRAIN_FILE_LIST: "data/COCO2014/ImageSets/train.txt"
    VAL_FILE_LIST: "data/COCO2014/VOC_ImageSets/val.txt"
    SEPARATOR: " "
    IGNORE_INDEX: 255
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
TEST:
    TEST_MODEL: "snapshots/coco_v1/final"
TRAIN:
    MODEL_SAVE_DIR: "snapshots/coco_v1/"
    PRETRAINED_MODEL: "pretrain/xception65_pretrained/"
    RESUME: False
    SNAPSHOT_EPOCH: 5
SOLVER:
    LR: 0.007
    WEIGHT_DECAY: 0.00004
    NUM_EPOCHS: 40
    LR_POLICY: "poly"
    OPTIMIZER: "SGD"
